#!/usr/bin/env ruby

##############################################################
#                                                            #
# Written by Patrick Hof <courts@offensivethinking.org>      #
# http://www.offensivethinking.org                           #
#                                                            #
# This software is licensed under the Creative               #
# Commons CC0 1.0 Universal License.                         #
# To view a copy of this license, visit                      #
# http://creativecommons.org/publicdomain/zero/1.0/legalcode #
#                                                            #
##############################################################

# "bitify" is a simple command line script to shorten a URL with http://bit.ly.
# It screen-scrapes the web site, so you don't need an account.

require 'open-uri'

unless ARGV[0]
  puts "Usage: #{__FILE__} <URL>"
  exit
end

site = open("http://bit.ly/?url=#{ARGV[0]}").read()
site =~ /shortUrl": "(http.*?)",/
puts $1
